/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/team-detail`; params?: Router.UnknownInputParams; } | { pathname: `/../components/LightningFlash`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ParticleEffect`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RoomListView`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GameRoomView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbot` | `/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/teams` | `/teams`; params?: Router.UnknownInputParams; } | { pathname: `/game/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/games/[league]`, params: Router.UnknownInputParams & { league: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/team-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/LightningFlash`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ParticleEffect`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/RoomListView`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/GameRoomView`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chatbot` | `/chatbot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/teams` | `/teams`; params?: Router.UnknownOutputParams; } | { pathname: `/game/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/games/[league]`, params: Router.UnknownOutputParams & { league: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/team-detail${`?${string}` | `#${string}` | ''}` | `/../components/LightningFlash${`?${string}` | `#${string}` | ''}` | `/../components/ParticleEffect${`?${string}` | `#${string}` | ''}` | `/../components/RoomListView${`?${string}` | `#${string}` | ''}` | `/../components/GameRoomView${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chatbot${`?${string}` | `#${string}` | ''}` | `/chatbot${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/teams${`?${string}` | `#${string}` | ''}` | `/teams${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/team-detail`; params?: Router.UnknownInputParams; } | { pathname: `/../components/LightningFlash`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ParticleEffect`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RoomListView`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GameRoomView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbot` | `/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/teams` | `/teams`; params?: Router.UnknownInputParams; } | `/game/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/games/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/game/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/games/[league]`, params: Router.UnknownInputParams & { league: string | number; } };
    }
  }
}
